name: Auto Tweet Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  post-tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

    #   - name: Install dotenv
    #     run: npm install dotenv

    #   - name: Install @google/generative-ai
    #     run: npm install @google/generative-ai

    #   - name: Install playwright
    #     run: npm install playwright

      - name: Install dependencies
        run: npm ci 

    #   - name: Install remaining dependencies
    #     run: npm install


      - name: Create .env file from GitHub secrets
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "TWITTER_USERNAME=${{ secrets.TWITTER_USERNAME }}" >> .env
          echo "TWITTER_PASSWORD=${{ secrets.TWITTER_PASSWORD }}" >> .env
          echo "TWITTER_PHONE=${{ secrets.TWITTER_PHONE }}" >> .env

      - name: Run Twitter Bot
        run: npx ts-node twitter-bot.ts
